/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.CandidateController;
import Controller.FormEvent;
import Controller.FormListener;
import Controller.MainController;
import Model.Candidate;
import java.awt.Toolkit;
import javax.swing.JPanel;
import View.Frame_Login;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Image;
import java.awt.LayoutManager;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class AdminMenu extends javax.swing.JFrame {
    
    Frame_Login login;
    ImageIcon iconAdd, iconEdit, iconDelete, iconView, iconArchive, iconLogout;
//    JPanel AddBTN;
    AdminMainContentArea adminmaincontentarea;
//    ImageIcon icon;
    //TODO: change this to main controller due to ElecPerController errors for now
    CandidateController candidate_controller = new CandidateController();

    
    /**
     * Creates new form AdminMenu
     */
    public AdminMenu() {
        initComponents();
        this.pack();
        Toolkit tk = Toolkit.getDefaultToolkit();
        int xsize = (int) tk.getScreenSize().getWidth();
        int ysize = (int) tk.getScreenSize().getHeight();
        this.setSize(xsize, ysize);
        this.setLocationRelativeTo(null);
        
        //Icons
        iconAdd = new ImageIcon("src/Icons/add128px.png");
        iconEdit = new ImageIcon("src/Icons/edit128px.png");
        iconDelete = new ImageIcon("src/Icons/delete128px.png");
        iconView = new ImageIcon("src/Icons/view2_128px.png");
        iconArchive = new ImageIcon("src/Icons/archive128px.png");
        iconLogout = new ImageIcon("src/Icons/logout128px.png");
        
        addIcon.setIcon(iconAdd);
        editIcon.setIcon(iconEdit);
        deleteIcon.setIcon(iconDelete);
        viewIcon.setIcon(iconView);
        archiveIcon.setIcon(iconArchive);
        logoutIcon.setIcon(iconLogout);

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AdminBackground = new javax.swing.JPanel();
        AdminHeader = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        UserContentR1 = new javax.swing.JPanel();
        AddBTN = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        addIcon = new javax.swing.JLabel();
        EditBTN = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        editIcon = new javax.swing.JLabel();
        DeleteBTN = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        deleteIcon = new javax.swing.JLabel();
        UserContentR2 = new javax.swing.JPanel();
        ViewBTN = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        viewIcon = new javax.swing.JLabel();
        ArchiveBTN = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        archiveIcon = new javax.swing.JLabel();
        LogoutBTN = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        logoutIcon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AdminBackground.setBackground(new java.awt.Color(33, 97, 140));
        AdminBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AdminHeader.setBackground(new java.awt.Color(33, 97, 140));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 60)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Welcome Admin!");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Choose from the admin");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("option below by clicking the button");

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 10));

        javax.swing.GroupLayout AdminHeaderLayout = new javax.swing.GroupLayout(AdminHeader);
        AdminHeader.setLayout(AdminHeaderLayout);
        AdminHeaderLayout.setHorizontalGroup(
            AdminHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminHeaderLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(AdminHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AdminHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 1395, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(1361, Short.MAX_VALUE))
        );
        AdminHeaderLayout.setVerticalGroup(
            AdminHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdminHeaderLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        AdminBackground.add(AdminHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 300));

        UserContentR1.setBackground(new java.awt.Color(33, 97, 140));
        UserContentR1.setLayout(new java.awt.GridLayout(1, 3, 150, 0));

        AddBTN.setBackground(new java.awt.Color(255, 255, 255));
        AddBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        AddBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddBTNMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AddBTNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AddBTNMouseExited(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Add Candidate");

        addIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout AddBTNLayout = new javax.swing.GroupLayout(AddBTN);
        AddBTN.setLayout(AddBTNLayout);
        AddBTNLayout.setHorizontalGroup(
            AddBTNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddBTNLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
        );
        AddBTNLayout.setVerticalGroup(
            AddBTNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddBTNLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(addIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        UserContentR1.add(AddBTN);

        EditBTN.setBackground(new java.awt.Color(255, 255, 255));
        EditBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditBTNMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EditBTNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EditBTNMouseExited(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Edit Candidate Details");

        editIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout EditBTNLayout = new javax.swing.GroupLayout(EditBTN);
        EditBTN.setLayout(EditBTNLayout);
        EditBTNLayout.setHorizontalGroup(
            EditBTNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EditBTNLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(editIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
        );
        EditBTNLayout.setVerticalGroup(
            EditBTNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EditBTNLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(editIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        UserContentR1.add(EditBTN);

        DeleteBTN.setBackground(new java.awt.Color(255, 255, 255));
        DeleteBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteBTNMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DeleteBTNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DeleteBTNMouseExited(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Delete Candidate");

        deleteIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout DeleteBTNLayout = new javax.swing.GroupLayout(DeleteBTN);
        DeleteBTN.setLayout(DeleteBTNLayout);
        DeleteBTNLayout.setHorizontalGroup(
            DeleteBTNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DeleteBTNLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(deleteIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
        );
        DeleteBTNLayout.setVerticalGroup(
            DeleteBTNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DeleteBTNLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(deleteIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        UserContentR1.add(DeleteBTN);

        AdminBackground.add(UserContentR1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 1340, 210));

        UserContentR2.setBackground(new java.awt.Color(33, 97, 140));
        UserContentR2.setLayout(new java.awt.GridLayout(1, 3, 150, 0));

        ViewBTN.setBackground(new java.awt.Color(255, 255, 255));
        ViewBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ViewBTNMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ViewBTNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ViewBTNMouseExited(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("View Data");

        viewIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout ViewBTNLayout = new javax.swing.GroupLayout(ViewBTN);
        ViewBTN.setLayout(ViewBTNLayout);
        ViewBTNLayout.setHorizontalGroup(
            ViewBTNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ViewBTNLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(viewIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );
        ViewBTNLayout.setVerticalGroup(
            ViewBTNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ViewBTNLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(viewIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        UserContentR2.add(ViewBTN);

        ArchiveBTN.setBackground(new java.awt.Color(255, 255, 255));
        ArchiveBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ArchiveBTNMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ArchiveBTNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ArchiveBTNMouseExited(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Archive Data");

        archiveIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout ArchiveBTNLayout = new javax.swing.GroupLayout(ArchiveBTN);
        ArchiveBTN.setLayout(ArchiveBTNLayout);
        ArchiveBTNLayout.setHorizontalGroup(
            ArchiveBTNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(ArchiveBTNLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(archiveIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );
        ArchiveBTNLayout.setVerticalGroup(
            ArchiveBTNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ArchiveBTNLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(archiveIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        UserContentR2.add(ArchiveBTN);

        LogoutBTN.setBackground(new java.awt.Color(255, 255, 255));
        LogoutBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutBTNMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LogoutBTNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LogoutBTNMouseExited(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Logout");

        logoutIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout LogoutBTNLayout = new javax.swing.GroupLayout(LogoutBTN);
        LogoutBTN.setLayout(LogoutBTNLayout);
        LogoutBTNLayout.setHorizontalGroup(
            LogoutBTNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LogoutBTNLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoutIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
        );
        LogoutBTNLayout.setVerticalGroup(
            LogoutBTNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LogoutBTNLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(logoutIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        UserContentR2.add(LogoutBTN);

        AdminBackground.add(UserContentR2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 590, 1340, 210));

        getContentPane().add(AdminBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1990, 1080));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ViewBTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewBTNMouseExited
        // TODO add your handling code here:
        resetColor(ViewBTN);
    }//GEN-LAST:event_ViewBTNMouseExited

    private void ViewBTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewBTNMouseEntered
        // TODO add your handling code here:
        setColor(ViewBTN);
    }//GEN-LAST:event_ViewBTNMouseEntered

    private void ViewBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewBTNMouseClicked
        // TODO add your handling code here:
        adminmaincontentarea = new AdminMainContentArea();
        adminmaincontentarea.setVisible(true);
        adminmaincontentarea.setCard("cardViewCandidates");
        this.setVisible(false);
        
    }//GEN-LAST:event_ViewBTNMouseClicked

    private void EditBTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditBTNMouseExited
        // TODO add your handling code here:
        resetColor(EditBTN);
    }//GEN-LAST:event_EditBTNMouseExited

    private void EditBTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditBTNMouseEntered
        // TODO add your handling code here:
        setColor(EditBTN);
    }//GEN-LAST:event_EditBTNMouseEntered

    private void EditBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditBTNMouseClicked
        adminmaincontentarea = new AdminMainContentArea();
        adminmaincontentarea.setVisible(true);
        adminmaincontentarea.setCard("cardAddCandidate");
        this.setVisible(false);
        
//        AddGUI edit_candidate = new AddGUI();
//        
//        // Set candidate here
//        Candidate to_edit = candidate_controller.query_candidate_by_id(1);
//        edit_candidate.set_candidate_details(to_edit);
//        
//        edit_candidate.set_form_listener(new FormListener() {
//            @Override           
//            public void formEventOccurred(FormEvent e) {
//                Boolean is_successful = candidate_controller.update_candidate(to_edit.get_candidate_id(), 
//                                                                              e.getCandidate());
//                
//                if(!is_successful)
//                {
//                    // TODO: possibly change message if there is a better message/design
//                    // Candidates are specifically unique by ID, fname, lname, sex and birthdate
//                    JOptionPane.showMessageDialog(null, 
//                                                  "A candidate with similar information already exists",
//                                                  "Add Candidate failed!",
//                                                  JOptionPane.ERROR_MESSAGE);
//                }
//            }
//        });
//        edit_candidate.setVisible(true);
//        this.setVisible(false);
    }//GEN-LAST:event_EditBTNMouseClicked

    private void ArchiveBTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ArchiveBTNMouseExited
        // TODO add your handling code here:
        resetColor(ArchiveBTN);
    }//GEN-LAST:event_ArchiveBTNMouseExited

    private void ArchiveBTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ArchiveBTNMouseEntered
        // TODO add your handling code here:
        setColor(ArchiveBTN);
    }//GEN-LAST:event_ArchiveBTNMouseEntered

    private void ArchiveBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ArchiveBTNMouseClicked
        // TODO add your handling code here:
        adminmaincontentarea = new AdminMainContentArea();
        adminmaincontentarea.setVisible(true);
        adminmaincontentarea.setCard("cardViewElec");
        this.setVisible(false);
    }//GEN-LAST:event_ArchiveBTNMouseClicked

    private void DeleteBTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteBTNMouseExited
        // TODO add your handling code here:
        resetColor(DeleteBTN);
    }//GEN-LAST:event_DeleteBTNMouseExited

    private void DeleteBTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteBTNMouseEntered
        // TODO add your handling code here:
        setColor(DeleteBTN);
    }//GEN-LAST:event_DeleteBTNMouseEntered

    private void DeleteBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteBTNMouseClicked
        // TODO add your handling code here:
        adminmaincontentarea = new AdminMainContentArea();
        adminmaincontentarea.setVisible(true);
        adminmaincontentarea.setCard("cardViewCandidates");
        this.setVisible(false);
    }//GEN-LAST:event_DeleteBTNMouseClicked

    private void LogoutBTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutBTNMouseExited
        // TODO add your handling code here:
        resetColor(LogoutBTN);
    }//GEN-LAST:event_LogoutBTNMouseExited

    private void LogoutBTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutBTNMouseEntered
        // TODO add your handling code here:
        setColor(LogoutBTN);
    }//GEN-LAST:event_LogoutBTNMouseEntered

    private void LogoutBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutBTNMouseClicked
        // TODO add your handling code here:
        login = new Frame_Login();
        login.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_LogoutBTNMouseClicked

    private void AddBTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddBTNMouseExited
        // TODO add your handling code here:
        resetColor(AddBTN);
    }//GEN-LAST:event_AddBTNMouseExited

    private void AddBTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddBTNMouseEntered
        // TODO add your handling code here:
        setColor(AddBTN);
    }//GEN-LAST:event_AddBTNMouseEntered

    private void AddBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddBTNMouseClicked
        // TODO add your handling code here:
        adminmaincontentarea = new AdminMainContentArea();
        adminmaincontentarea.setVisible(true);
        adminmaincontentarea.setCard("cardAddCandidate");
        this.setVisible(false);

        //        AddGUI add_new_candidate = new AddGUI();
        //        add_new_candidate.set_form_listener(new FormListener() {
            //            @Override
            //            public void formEventOccurred(FormEvent e) {
                //                Boolean is_successful = candidate_controller.add_candidate(e);
                //
                //                if(!is_successful)
                //                {
                    //                    // TODO: possibly change message if there is a better message/design
                    //                    // Candidates are specifically unique by ID, fname, lname, sex and birthdate
                    //                    JOptionPane.showMessageDialog(null,
                        //                                                  "A candidate with similar information already exists",
                        //                                                  "Add Candidate failed!",
                        //                                                  JOptionPane.ERROR_MESSAGE);
                    //                } else
                //                {
                    //                    JOptionPane.showMessageDialog(null,
                        //                                                  "Candidate has been successfully added.",
                        //                                                  "Successfully Added Candidate!",
                        //                                                  JOptionPane.ERROR_MESSAGE);
                    //                }
                //            }
            //        });
    //        add_new_candidate.setVisible(true);
    //        setVisible(false);
    }//GEN-LAST:event_AddBTNMouseClicked

    public void setColor(JPanel panel){
        panel.setBackground(new java.awt.Color(211,211,211));
    }
    
    public void resetColor(JPanel panel){
        panel.setBackground(new java.awt.Color(255, 255, 255));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddBTN;
    private javax.swing.JPanel AdminBackground;
    private javax.swing.JPanel AdminHeader;
    private javax.swing.JPanel ArchiveBTN;
    private javax.swing.JPanel DeleteBTN;
    private javax.swing.JPanel EditBTN;
    private javax.swing.JPanel LogoutBTN;
    private javax.swing.JPanel UserContentR1;
    private javax.swing.JPanel UserContentR2;
    private javax.swing.JPanel ViewBTN;
    private javax.swing.JLabel addIcon;
    private javax.swing.JLabel archiveIcon;
    private javax.swing.JLabel deleteIcon;
    private javax.swing.JLabel editIcon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel logoutIcon;
    private javax.swing.JLabel viewIcon;
    // End of variables declaration//GEN-END:variables
}