/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ElecPerController;
import Controller.FormEvent;
import Controller.FormListener;
import Controller.MainController;
import Model.ElecPer;
import Model.ElecPerSQL;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dandani-cs
 */
public class ArchiveGUIPanel extends javax.swing.JPanel {
    FormListener form_listener;
    /**
     * Creates new form ArchiveGUIPanel
     */
    public ArchiveGUIPanel(MainController main_controller) {
        initComponents();
        
        this.setSize(new Dimension(1620,1080));
        
        DefaultTableModel dataModel = new DefaultTableModel(ElecPerSQL.getTable(),
                new String[] {"ELECPERID", "Name", "Starting Date", "Finish Date", "Archive"}) {
                        @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }                
            
        };
        datatable.setModel(dataModel);
        //datatable.setAutoCreateRowSorter(true);
        
        datatable.getTableHeader().setFont(new Font("Franklin Gothic Medium", Font.PLAIN, 15));
        datatable.getTableHeader().setBackground(new Color(255,255,255));
        datatable.getTableHeader().setForeground(new Color(33,82,117));
        datatable.setRowHeight(25);
        
        datatable.setGridColor(new Color(33,82,117));
        datatable.setShowHorizontalLines(true);
        datatable.setShowVerticalLines(true);
               
        DefaultTableCellRenderer tableCellRenderer = new DefaultTableCellRenderer();
        tableCellRenderer.setHorizontalAlignment(JLabel.CENTER);
        tableCellRenderer.setBackground(Color.white);
        
        for(int i = 0; i < datatable.getColumnModel().getColumnCount(); i++) {
            datatable.getColumnModel().getColumn(i).setCellRenderer(tableCellRenderer);            
        }
        datatable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        datatable.getColumnModel().getColumn(4).setCellRenderer(datatable.getDefaultRenderer(java.lang.Boolean.class));
        datatable.removeColumn(datatable.getColumnModel().getColumn(0));
    }

    public void setFormListener(FormListener form_listener) {
        this.form_listener = form_listener;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        archivecardBG = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        datatable = new javax.swing.JTable();
        archiveBTN = new javax.swing.JButton();
        archivetitle = new javax.swing.JLabel();
        archivesubtitle = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();

        archivecardBG.setBackground(new java.awt.Color(255, 255, 255));

        datatable.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        datatable.setForeground(new java.awt.Color(33, 82, 117));
        datatable.setGridColor(new java.awt.Color(0, 51, 51));
        datatable.setRowHeight(20);
        datatable.setSelectionBackground(new java.awt.Color(33, 82, 117));
        datatable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                datatableMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(datatable);

        archiveBTN.setBackground(new java.awt.Color(255, 255, 255));
        archiveBTN.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 15)); // NOI18N
        archiveBTN.setForeground(new java.awt.Color(33, 82, 117));
        archiveBTN.setText("Add New Election");
        archiveBTN.setBorderPainted(false);
        archiveBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        archiveBTN.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        archiveBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                archiveBTNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                archiveBTNMouseExited(evt);
            }
        });
        archiveBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                archiveBTNActionPerformed(evt);
            }
        });

        archivetitle.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 30)); // NOI18N
        archivetitle.setForeground(new java.awt.Color(33, 82, 117));
        archivetitle.setText("MANAGE DATA BY ELECTION PERIOD");

        archivesubtitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        archivesubtitle.setForeground(new java.awt.Color(33, 82, 117));
        archivesubtitle.setText("Select the Election Period/s to archive from the data table below.");

        javax.swing.GroupLayout archivecardBGLayout = new javax.swing.GroupLayout(archivecardBG);
        archivecardBG.setLayout(archivecardBGLayout);
        archivecardBGLayout.setHorizontalGroup(
            archivecardBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(archivecardBGLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(archivecardBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(archivesubtitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(archivecardBGLayout.createSequentialGroup()
                        .addComponent(archivetitle)
                        .addGap(0, 1016, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(archivecardBGLayout.createSequentialGroup()
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 1211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 417, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, archivecardBGLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(archiveBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(473, 473, 473))
            .addGroup(archivecardBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(archivecardBGLayout.createSequentialGroup()
                    .addGap(79, 79, 79)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1080, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(469, Short.MAX_VALUE)))
        );
        archivecardBGLayout.setVerticalGroup(
            archivecardBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, archivecardBGLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(archivetitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(archivesubtitle)
                .addGap(52, 52, 52)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 602, Short.MAX_VALUE)
                .addComponent(archiveBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(260, 260, 260))
            .addGroup(archivecardBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(archivecardBGLayout.createSequentialGroup()
                    .addGap(307, 307, 307)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(308, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1620, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(archivecardBG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1081, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(archivecardBG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void datatableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_datatableMousePressed
        if(evt.getClickCount() == 1) {
            boolean setArchived = false;

            boolean archived = (boolean) datatable.getModel().getValueAt(datatable.getSelectedRow(), 4);
            if(archived == true) {
                datatable.getModel().setValueAt(setArchived, datatable.getSelectedRow(), 4);
            } else {
                setArchived = true;
                datatable.getModel().setValueAt(setArchived, datatable.getSelectedRow(), 4);
            }

            ElecPer ep = new ElecPer();
            ep.setElecPerId((int) datatable.getModel().getValueAt(datatable.getSelectedRow(), 0));
            ep.setArchived(setArchived);
            FormEvent e = new FormEvent(evt, ep);
            ElecPerController epc = new ElecPerController();
            epc.archivedElectionPeriod(e);
        }
    }//GEN-LAST:event_datatableMousePressed

    private void archiveBTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_archiveBTNMouseEntered
        // TODO add your handling code here:
        Color hoverBTN = new Color(15,43,61);

        archiveBTN.setBackground(hoverBTN);
        archiveBTN.setForeground(Color.WHITE);
    }//GEN-LAST:event_archiveBTNMouseEntered

    private void archiveBTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_archiveBTNMouseExited
        // TODO add your handling code here:
        Color byeBTN = new Color(0,51,51);

        archiveBTN.setBackground(Color.WHITE);
        archiveBTN.setForeground(byeBTN);
    }//GEN-LAST:event_archiveBTNMouseExited

    private void archiveBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_archiveBTNActionPerformed
        // TODO add your handling code here:
        System.out.println("archive btn");
        FormEvent ev = new FormEvent(evt, "cardAddElec");
        form_listener.formEventOccurred(ev);
    }//GEN-LAST:event_archiveBTNActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton archiveBTN;
    private javax.swing.JPanel archivecardBG;
    private javax.swing.JLabel archivesubtitle;
    private javax.swing.JLabel archivetitle;
    private javax.swing.JTable datatable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator5;
    // End of variables declaration//GEN-END:variables
}
