/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ElecPerController;
import Controller.FormEvent;
import Controller.MainController;
import Model.ElecPer;
import Model.ElecPerSQL;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.Date;
import javax.swing.BorderFactory;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultCellEditor;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.UIDefaults;
import javax.swing.UIManager;
import javax.swing.border.EtchedBorder;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author caeth
 */
public class Archive extends javax.swing.JFrame {    
    
    private Color hoverMENU = new Color(33,82,117);
    private Color byeMENU = new Color(33,97,140);
    

    /**
     * Creates new form Archive
     */
    public Archive() {
        initComponents();
        
        this.setSize(new Dimension(1920,1080));
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        DefaultTableModel dataModel = new DefaultTableModel(ElecPerSQL.getTable(),
                new String[] {"ELECPERID", "Name", "Starting Date", "Finish Date", "Archive"}) {
                        @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }                
            
        };
        datatable.setModel(dataModel);
        //datatable.setAutoCreateRowSorter(true);
        
        
        datatable.getTableHeader().setFont(new Font("Franklin Gothic Medium", Font.PLAIN, 15));
        datatable.getTableHeader().setBackground(new Color(255,255,255));
        datatable.getTableHeader().setForeground(new Color(33,82,117));
        datatable.setRowHeight(25);
        
        datatable.setGridColor(new Color(33,82,117));
        datatable.setShowHorizontalLines(true);
        datatable.setShowVerticalLines(true);
               
        DefaultTableCellRenderer tableCellRenderer = new DefaultTableCellRenderer();
        tableCellRenderer.setHorizontalAlignment(JLabel.CENTER);
        tableCellRenderer.setBackground(Color.white);
        
        
        for(int i = 0; i < datatable.getColumnModel().getColumnCount(); i++) {
            datatable.getColumnModel().getColumn(i).setCellRenderer(tableCellRenderer);            
        }
        datatable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        datatable.getColumnModel().getColumn(4).setCellRenderer(datatable.getDefaultRenderer(java.lang.Boolean.class));
        datatable.removeColumn(datatable.getColumnModel().getColumn(0));
       
    }

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        sidePNL = new javax.swing.JPanel();
        vCandidate = new javax.swing.JPanel();
        sp1LBL = new javax.swing.JLabel();
        vElection2 = new javax.swing.JPanel();
        sp2LBL2 = new javax.swing.JLabel();
        back = new javax.swing.JPanel();
        sp3LBL = new javax.swing.JLabel();
        logout = new javax.swing.JPanel();
        sp3LBL1 = new javax.swing.JLabel();
        archivecardBG = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        datatable = new javax.swing.JTable();
        archiveBTN = new javax.swing.JButton();
        archivetitle = new javax.swing.JLabel();
        archivesubtitle = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Election Candidates Record Management");

        bg.setBackground(new java.awt.Color(204, 204, 204));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidePNL.setBackground(new java.awt.Color(33, 97, 140));

        vCandidate.setBackground(new java.awt.Color(33, 97, 140));
        vCandidate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                vCandidateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                vCandidateMouseExited(evt);
            }
        });

        sp1LBL.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 16)); // NOI18N
        sp1LBL.setForeground(new java.awt.Color(255, 255, 255));
        sp1LBL.setText(" VIEW CANDIDATES");

        javax.swing.GroupLayout vCandidateLayout = new javax.swing.GroupLayout(vCandidate);
        vCandidate.setLayout(vCandidateLayout);
        vCandidateLayout.setHorizontalGroup(
            vCandidateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vCandidateLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(sp1LBL, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        vCandidateLayout.setVerticalGroup(
            vCandidateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, vCandidateLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sp1LBL, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addContainerGap())
        );

        vElection2.setBackground(new java.awt.Color(33, 97, 140));
        vElection2.setPreferredSize(new java.awt.Dimension(250, 69));
        vElection2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                vElection2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                vElection2MouseExited(evt);
            }
        });

        sp2LBL2.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 16)); // NOI18N
        sp2LBL2.setForeground(new java.awt.Color(255, 255, 255));
        sp2LBL2.setText(" VIEW ELECTIONS");

        javax.swing.GroupLayout vElection2Layout = new javax.swing.GroupLayout(vElection2);
        vElection2.setLayout(vElection2Layout);
        vElection2Layout.setHorizontalGroup(
            vElection2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vElection2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(sp2LBL2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        vElection2Layout.setVerticalGroup(
            vElection2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vElection2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(sp2LBL2)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        back.setBackground(new java.awt.Color(33, 97, 140));
        back.setPreferredSize(new java.awt.Dimension(250, 69));
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backMouseExited(evt);
            }
        });

        sp3LBL.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 16)); // NOI18N
        sp3LBL.setForeground(new java.awt.Color(255, 255, 255));
        sp3LBL.setText(" BACK TO MAIN MENU");

        javax.swing.GroupLayout backLayout = new javax.swing.GroupLayout(back);
        back.setLayout(backLayout);
        backLayout.setHorizontalGroup(
            backLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(sp3LBL)
                .addContainerGap(94, Short.MAX_VALUE))
        );
        backLayout.setVerticalGroup(
            backLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(sp3LBL)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        logout.setBackground(new java.awt.Color(33, 97, 140));
        logout.setPreferredSize(new java.awt.Dimension(250, 69));
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutMouseExited(evt);
            }
        });

        sp3LBL1.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 16)); // NOI18N
        sp3LBL1.setForeground(new java.awt.Color(255, 255, 255));
        sp3LBL1.setText(" LOGOUT");

        javax.swing.GroupLayout logoutLayout = new javax.swing.GroupLayout(logout);
        logout.setLayout(logoutLayout);
        logoutLayout.setHorizontalGroup(
            logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoutLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(sp3LBL1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );
        logoutLayout.setVerticalGroup(
            logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoutLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(sp3LBL1)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout sidePNLLayout = new javax.swing.GroupLayout(sidePNL);
        sidePNL.setLayout(sidePNLLayout);
        sidePNLLayout.setHorizontalGroup(
            sidePNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(vCandidate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(vElection2, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
            .addComponent(back, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
            .addComponent(logout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
        sidePNLLayout.setVerticalGroup(
            sidePNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePNLLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(vCandidate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(vElection2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 692, Short.MAX_VALUE))
        );

        bg.add(sidePNL, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 1080));

        archivecardBG.setBackground(new java.awt.Color(255, 255, 255));

        datatable.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        datatable.setForeground(new java.awt.Color(33, 82, 117));
        datatable.setGridColor(new java.awt.Color(0, 0, 0));
        datatable.setRowHeight(20);
        datatable.setSelectionBackground(new java.awt.Color(33, 82, 117));
        datatable.getTableHeader().setReorderingAllowed(false);
        datatable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                datatableMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(datatable);

        archiveBTN.setBackground(new java.awt.Color(255, 255, 255));
        archiveBTN.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 15)); // NOI18N
        archiveBTN.setForeground(new java.awt.Color(33, 82, 117));
        archiveBTN.setText("Archive Data");
        archiveBTN.setBorderPainted(false);
        archiveBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        archiveBTN.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        archiveBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                archiveBTNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                archiveBTNMouseExited(evt);
            }
        });
        archiveBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                archiveBTNActionPerformed(evt);
            }
        });

        archivetitle.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 30)); // NOI18N
        archivetitle.setForeground(new java.awt.Color(33, 82, 117));
        archivetitle.setText("MANAGE DATA BY ELECTION PERIOD");

        archivesubtitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        archivesubtitle.setForeground(new java.awt.Color(33, 82, 117));
        archivesubtitle.setText("Select the Election Period/s to archive from the data table below.");

        javax.swing.GroupLayout archivecardBGLayout = new javax.swing.GroupLayout(archivecardBG);
        archivecardBG.setLayout(archivecardBGLayout);
        archivecardBGLayout.setHorizontalGroup(
            archivecardBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(archivecardBGLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(archivecardBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(archivecardBGLayout.createSequentialGroup()
                        .addGroup(archivecardBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(archiveBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(79, 79, 79))
                    .addGroup(archivecardBGLayout.createSequentialGroup()
                        .addGroup(archivecardBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(archivesubtitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(archivecardBGLayout.createSequentialGroup()
                                .addComponent(archivetitle)
                                .addGap(0, 1006, Short.MAX_VALUE)))
                        .addContainerGap())))
            .addGroup(archivecardBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(archivecardBGLayout.createSequentialGroup()
                    .addGap(79, 79, 79)
                    .addComponent(jScrollPane1)
                    .addGap(80, 80, 80)))
        );
        archivecardBGLayout.setVerticalGroup(
            archivecardBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, archivecardBGLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(archivetitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(archivesubtitle)
                .addGap(52, 52, 52)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 659, Short.MAX_VALUE)
                .addComponent(archiveBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(202, 202, 202))
            .addGroup(archivecardBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(archivecardBGLayout.createSequentialGroup()
                    .addGap(307, 307, 307)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(308, Short.MAX_VALUE)))
        );

        bg.add(archivecardBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 1620, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 1080, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void archiveBTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_archiveBTNMouseEntered
        // TODO add your handling code here:
        Color hoverBTN = new Color(15,43,61);
        
        archiveBTN.setBackground(hoverBTN);
        archiveBTN.setForeground(Color.WHITE);
    }//GEN-LAST:event_archiveBTNMouseEntered

    private void archiveBTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_archiveBTNMouseExited
        // TODO add your handling code here:
        Color byeBTN = new Color(0,51,51);
        
        archiveBTN.setBackground(Color.WHITE);
        archiveBTN.setForeground(byeBTN);
    }//GEN-LAST:event_archiveBTNMouseExited

    private void archiveBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_archiveBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_archiveBTNActionPerformed

    private void vCandidateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vCandidateMouseEntered
        // TODO add your handling code here:
        vCandidate.setBackground(hoverMENU);
    }//GEN-LAST:event_vCandidateMouseEntered

    private void vCandidateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vCandidateMouseExited
        // TODO add your handling code here:
        vCandidate.setBackground(byeMENU);
    }//GEN-LAST:event_vCandidateMouseExited

    private void vElection2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vElection2MouseEntered
        // TODO add your handling code here:
        vElection2.setBackground(hoverMENU);
    }//GEN-LAST:event_vElection2MouseEntered

    private void vElection2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vElection2MouseExited
        // TODO add your handling code here:
        vElection2.setBackground(byeMENU);
    }//GEN-LAST:event_vElection2MouseExited

    private void backMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseEntered
        // TODO add your handling code here:
        back.setBackground(hoverMENU);
    }//GEN-LAST:event_backMouseEntered

    private void backMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseExited
        // TODO add your handling code here:
        back.setBackground(byeMENU);
    }//GEN-LAST:event_backMouseExited

    private void logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseEntered
        // TODO add your handling code here:
        logout.setBackground(hoverMENU);
    }//GEN-LAST:event_logoutMouseEntered

    private void logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseExited
        // TODO add your handling code here:
        logout.setBackground(byeMENU);
    }//GEN-LAST:event_logoutMouseExited

    private void datatableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_datatableMousePressed
        if(evt.getClickCount() == 1) {
            boolean setArchived = false;
            
            boolean archived = (boolean) datatable.getModel().getValueAt(datatable.getSelectedRow(), 4);
            if(archived == true) {
                datatable.getModel().setValueAt(setArchived, datatable.getSelectedRow(), 4);
            } else {
                setArchived = true;
                datatable.getModel().setValueAt(setArchived, datatable.getSelectedRow(), 4);
            }
            
            ElecPer ep = new ElecPer();
            ep.setElecPerId((int) datatable.getModel().getValueAt(datatable.getSelectedRow(), 0));
            ep.setArchived(setArchived);
            FormEvent e = new FormEvent(evt, ep);
            ElecPerController epc = new ElecPerController();
            epc.archivedElectionPeriod(e);
        }
    }//GEN-LAST:event_datatableMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Archive.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Archive.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Archive.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Archive.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Archive().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton archiveBTN;
    private javax.swing.JPanel archivecardBG;
    private javax.swing.JLabel archivesubtitle;
    private javax.swing.JLabel archivetitle;
    private javax.swing.JPanel back;
    private javax.swing.JPanel bg;
    private javax.swing.JTable datatable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JPanel logout;
    private javax.swing.JPanel sidePNL;
    private javax.swing.JLabel sp1LBL;
    private javax.swing.JLabel sp2LBL2;
    private javax.swing.JLabel sp3LBL;
    private javax.swing.JLabel sp3LBL1;
    private javax.swing.JPanel vCandidate;
    private javax.swing.JPanel vElection2;
    // End of variables declaration//GEN-END:variables
}
