/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author Admin
 */
public class UserMenu extends javax.swing.JFrame {

    Frame_Login login;
    UserMainContentArea usermaincontentarea;
    
    /** Creates new form UserMenu */
    public UserMenu() {
        initComponents();
        
        this.setSize(new Dimension(1920,1080));
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        this.pack();
        /*Toolkit tk = Toolkit.getDefaultToolkit();
        int xsize = (int) tk.getScreenSize().getWidth();
        int ysize = (int) tk.getScreenSize().getHeight();
        this.setSize(xsize, ysize);*/
        this.setLocationRelativeTo(null);
        
        candIcon.setIcon(new ImageIcon("src\\Icons\\candidate2_128px.png"));
        posIcon.setIcon(new ImageIcon("src\\Icons\\search128px.png"));
        partyIcon.setIcon(new ImageIcon("src\\Icons\\party128px.png"));
        viewIcon.setIcon(new ImageIcon("src\\Icons\\view128px.png"));
        logoutIcon.setIcon(new ImageIcon("src\\Icons\\logout128px.png"));

          
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UserBacground = new javax.swing.JPanel();
        UserHeader = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        UserContentR1 = new javax.swing.JPanel();
        CandSearchBTN = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        candIcon = new javax.swing.JLabel();
        PosSearchBTN = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        posIcon = new javax.swing.JLabel();
        PartySearchBTN = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        partyIcon = new javax.swing.JLabel();
        UserContentR2 = new javax.swing.JPanel();
        ViewAllBTN = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        viewIcon = new javax.swing.JLabel();
        LogoutBTN = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        logoutIcon = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UserBacground.setBackground(new java.awt.Color(33, 97, 140));
        UserBacground.setMinimumSize(new java.awt.Dimension(1920, 1080));
        UserBacground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UserHeader.setBackground(new java.awt.Color(33, 97, 140));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 60)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Welcome User!");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Choose from the user");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("option below by clicking the button");

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 10));

        javax.swing.GroupLayout UserHeaderLayout = new javax.swing.GroupLayout(UserHeader);
        UserHeader.setLayout(UserHeaderLayout);
        UserHeaderLayout.setHorizontalGroup(
            UserHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserHeaderLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(UserHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UserHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 1395, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(1361, Short.MAX_VALUE))
        );
        UserHeaderLayout.setVerticalGroup(
            UserHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UserHeaderLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        UserBacground.add(UserHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 320));

        UserContentR1.setBackground(new java.awt.Color(33, 97, 140));
        UserContentR1.setLayout(new java.awt.GridLayout(1, 3, 150, 0));

        CandSearchBTN.setBackground(new java.awt.Color(255, 255, 255));
        CandSearchBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        CandSearchBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CandSearchBTNMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CandSearchBTNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CandSearchBTNMouseExited(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Search a Candidate");

        candIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout CandSearchBTNLayout = new javax.swing.GroupLayout(CandSearchBTN);
        CandSearchBTN.setLayout(CandSearchBTNLayout);
        CandSearchBTNLayout.setHorizontalGroup(
            CandSearchBTNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(CandSearchBTNLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(candIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );
        CandSearchBTNLayout.setVerticalGroup(
            CandSearchBTNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CandSearchBTNLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(candIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        UserContentR1.add(CandSearchBTN);

        PosSearchBTN.setBackground(new java.awt.Color(255, 255, 255));
        PosSearchBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PosSearchBTNMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PosSearchBTNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PosSearchBTNMouseExited(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Search a Position");

        posIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout PosSearchBTNLayout = new javax.swing.GroupLayout(PosSearchBTN);
        PosSearchBTN.setLayout(PosSearchBTNLayout);
        PosSearchBTNLayout.setHorizontalGroup(
            PosSearchBTNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PosSearchBTNLayout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addComponent(posIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
        );
        PosSearchBTNLayout.setVerticalGroup(
            PosSearchBTNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PosSearchBTNLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(posIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        UserContentR1.add(PosSearchBTN);

        PartySearchBTN.setBackground(new java.awt.Color(255, 255, 255));
        PartySearchBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PartySearchBTNMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PartySearchBTNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PartySearchBTNMouseExited(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Search a Political Party");

        partyIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout PartySearchBTNLayout = new javax.swing.GroupLayout(PartySearchBTN);
        PartySearchBTN.setLayout(PartySearchBTNLayout);
        PartySearchBTNLayout.setHorizontalGroup(
            PartySearchBTNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PartySearchBTNLayout.createSequentialGroup()
                .addContainerGap(76, Short.MAX_VALUE)
                .addComponent(partyIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
        );
        PartySearchBTNLayout.setVerticalGroup(
            PartySearchBTNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PartySearchBTNLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(partyIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        UserContentR1.add(PartySearchBTN);

        UserBacground.add(UserContentR1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 1340, 220));

        UserContentR2.setBackground(new java.awt.Color(33, 97, 140));
        UserContentR2.setLayout(new java.awt.GridLayout(1, 3, 150, 0));

        ViewAllBTN.setBackground(new java.awt.Color(255, 255, 255));
        ViewAllBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ViewAllBTNMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ViewAllBTNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ViewAllBTNMouseExited(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("View All");

        viewIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout ViewAllBTNLayout = new javax.swing.GroupLayout(ViewAllBTN);
        ViewAllBTN.setLayout(ViewAllBTNLayout);
        ViewAllBTNLayout.setHorizontalGroup(
            ViewAllBTNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(ViewAllBTNLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(viewIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );
        ViewAllBTNLayout.setVerticalGroup(
            ViewAllBTNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ViewAllBTNLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(viewIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        UserContentR2.add(ViewAllBTN);

        LogoutBTN.setBackground(new java.awt.Color(255, 255, 255));
        LogoutBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutBTNMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LogoutBTNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LogoutBTNMouseExited(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Logout");

        logoutIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout LogoutBTNLayout = new javax.swing.GroupLayout(LogoutBTN);
        LogoutBTN.setLayout(LogoutBTNLayout);
        LogoutBTNLayout.setHorizontalGroup(
            LogoutBTNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
            .addGroup(LogoutBTNLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(logoutIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        LogoutBTNLayout.setVerticalGroup(
            LogoutBTNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LogoutBTNLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(logoutIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        UserContentR2.add(LogoutBTN);

        jPanel6.setBackground(new java.awt.Color(33, 97, 140));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 346, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );

        UserContentR2.add(jPanel6);

        UserBacground.add(UserContentR2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 590, 1340, 220));

        getContentPane().add(UserBacground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogoutBTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutBTNMouseExited
        // TODO add your handling code here:
        resetColor(LogoutBTN);
    }//GEN-LAST:event_LogoutBTNMouseExited

    private void LogoutBTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutBTNMouseEntered
        // TODO add your handling code here:
        setColor(LogoutBTN);
    }//GEN-LAST:event_LogoutBTNMouseEntered

    private void LogoutBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutBTNMouseClicked
        // TODO add your handling code here:
        login = new Frame_Login();
        login.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_LogoutBTNMouseClicked

    private void ViewAllBTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewAllBTNMouseExited
        // TODO add your handling code here:
        resetColor(ViewAllBTN);
    }//GEN-LAST:event_ViewAllBTNMouseExited

    private void ViewAllBTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewAllBTNMouseEntered
        // TODO add your handling code here:
        setColor(ViewAllBTN);
    }//GEN-LAST:event_ViewAllBTNMouseEntered

    private void ViewAllBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewAllBTNMouseClicked
        // TODO add your handling code here:
        usermaincontentarea = new UserMainContentArea();
        usermaincontentarea.setVisible(true);
        usermaincontentarea.setSearchCard("name_filter");
        this.setVisible(false);
    }//GEN-LAST:event_ViewAllBTNMouseClicked

    private void PartySearchBTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PartySearchBTNMouseExited
        // TODO add your handling code here:
        resetColor(PartySearchBTN);
    }//GEN-LAST:event_PartySearchBTNMouseExited

    private void PartySearchBTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PartySearchBTNMouseEntered
        // TODO add your handling code here:
        setColor(PartySearchBTN);
    }//GEN-LAST:event_PartySearchBTNMouseEntered

    private void PartySearchBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PartySearchBTNMouseClicked
        // TODO add your handling code here:
        usermaincontentarea = new UserMainContentArea();
        usermaincontentarea.setVisible(true);
        usermaincontentarea.setSearchCard("party_filter");
        this.setVisible(false);
    }//GEN-LAST:event_PartySearchBTNMouseClicked

    private void PosSearchBTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PosSearchBTNMouseExited
        // TODO add your handling code here:
        resetColor(PosSearchBTN);
    }//GEN-LAST:event_PosSearchBTNMouseExited

    private void PosSearchBTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PosSearchBTNMouseEntered
        // TODO add your handling code here:
        setColor(PosSearchBTN);
    }//GEN-LAST:event_PosSearchBTNMouseEntered

    private void PosSearchBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PosSearchBTNMouseClicked
        // TODO add your handling code here:
        usermaincontentarea = new UserMainContentArea();
        usermaincontentarea.setVisible(true);
        usermaincontentarea.setSearchCard("name_filter");
        this.setVisible(false);
    }//GEN-LAST:event_PosSearchBTNMouseClicked

    private void CandSearchBTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CandSearchBTNMouseExited
        // TODO add your handling code here:
        resetColor(CandSearchBTN);
    }//GEN-LAST:event_CandSearchBTNMouseExited

    private void CandSearchBTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CandSearchBTNMouseEntered
        // TODO add your handling code here:
        setColor(CandSearchBTN);
    }//GEN-LAST:event_CandSearchBTNMouseEntered

    private void CandSearchBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CandSearchBTNMouseClicked
        // TODO add your handling code here:
        usermaincontentarea = new UserMainContentArea();
        usermaincontentarea.setVisible(true);
        usermaincontentarea.setSearchCard("name_filter");
        this.setVisible(false);
       
    }//GEN-LAST:event_CandSearchBTNMouseClicked

    public void setColor(JPanel panel){
        panel.setBackground(new java.awt.Color(211,211,211));
    }
    
    public void resetColor(JPanel panel){
        panel.setBackground(new java.awt.Color(255, 255, 255));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CandSearchBTN;
    private javax.swing.JPanel LogoutBTN;
    private javax.swing.JPanel PartySearchBTN;
    private javax.swing.JPanel PosSearchBTN;
    private javax.swing.JPanel UserBacground;
    private javax.swing.JPanel UserContentR1;
    private javax.swing.JPanel UserContentR2;
    private javax.swing.JPanel UserHeader;
    private javax.swing.JPanel ViewAllBTN;
    private javax.swing.JLabel candIcon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel logoutIcon;
    private javax.swing.JLabel partyIcon;
    private javax.swing.JLabel posIcon;
    private javax.swing.JLabel viewIcon;
    // End of variables declaration//GEN-END:variables

}
